spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    streams:
      bootstrap-servers:
        - localhost:9092
        - 192.168.0.1:9092
topic: temperatureMeasurements
sensorNumber: 25
temperatureConfiguration:
  anomalyChance: 0.0001
  normalRangeMin: 22.0
  normalRangeMax: 23.0
  anomalyRangeMin: 22.2
  anomalyRangeMax: 29.0